name: "E2E"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  integration:
    name: "E2E"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        product:
          - "boto3"
          - "aioboto3"
          - "aiobotocore"
        python_version:
          - "3.8" # oldest supported
          - "3.10" # most popular
          - "3.13" # latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Integration tests
        run: |
          uv run scripts/integration.py \
            --product ${{ matrix.product }} \
            --python ${{ matrix.python_version }} \
            -d
